version: '3.2'

services:

  pipelines:
    depends_on:
    - redis
    - db
    - elasticsearch
    environment:
      DPP_DB_ENGINE: postgresql://postgres:123456@db:5432/postgres"
      DPP_REDIS_HOST: redis
      DPP_ELASTICSEARCH: elasticsearch:9200


  redis:
    image: redis:alpine

  db:
    image: postgres:9.6.3-alpine
    environment:
      - "POSTGRES_PASSWORD=123456"
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "15432:5432"

  elasticsearch:
    image: budgetkey/open-budget-elasticsearch
    ports:
    - "19200:9200"

  kibana:
    depends_on:
    - elasticsearch
    image: docker.elastic.co/kibana/kibana:5.3.0
    environment:
    - "ELASTICSEARCH_URL=http://elasticsearch:9200/"
    ports:
    - "15601:5601"

volumes:
  db:
