# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Test
      run: |
        docker build -t budgetkey-data-pipelines-tests tests
        docker run -v `pwd`/tests:/testenv/tests budgetkey-data-pipelines-tests
    - name: Build
      run: |
        ./ci.sh script
    - name: Deploy
      run: |
        ./ci.sh deploy
        ./ci.sh bump
